### ISSUE TITLE
'import_as_ref' macro attribute makes initializer inaccessible  in Swift

### ISSUE THREAD

**Issue by igorkravchenko** [AdaEngine/box2d-swift#1]
Hi! First of all thanks for this great Swift/C++ interoperability example. 

It seems that right now there's no way to create instance of `b2World` (and other C++ classes) in Swift.
Most likely this is related to `import_as_ref` [attribute](https://github.com/AdaEngine/box2d-swift/blob/38c5c68cc7073638cce540599f79ebb257d0bd02/Sources/box2d/include/box2d/b2_api.h#L54).
If this attribute is omitted, then `b2World.init(_ gravity: b2Vec2)` gets synthesized, but `b2World` is no longer a class but struct. 
Is there a way to enforce initializer synthesis for C++ classes while still keeping them as reference?

**Comment by SpectralDragon** [comment]
Hi! Sorry for late answer. 
It seems like we should try to remove `AS_SWIFT_CLASS` macro and try to use default C++ interop. I used that macro a long time ago, when C++ interop was in experimental mode, maybe in Swift 5.9 all troubles was resolved, but I 'm not sure about it...

**Comment by SpectralDragon** [comment]
@igorkravchenko Hi! 

I have updated box2d and now it full compatible to use in Swift project. 

You can check it here: [AdaEngine PhysicsWorld2D.swift](https://github.com/AdaEngine/AdaEngine/blob/main/Sources/AdaEngine/Scene/Physics/Physics2D/PhysicsWorld2D.swift)

If you have any question, please reopen issue.
